title: Rohit
logo: /assets/images/logo.avif
baseurl: /

typewriter_effect: false

collections:
  projects:
    output: true

rrss:
  email: "rkj2096@gmail.com"
  github: "https://github.com/rkj2096"
  # telegram: "https://t.me/"
  stackoverflow: "https://stackoverflow.com/rkj2096"
  discord: "https://discord.com/rkj2096"
  # mastodon: "https://lile.cl/"

plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-polyglot

languages: ["en"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

jekyll-archives:
  enabled:
    - categories
  layout: blog
  permalinks:
    category: "/category/:name/"

defaults:
  - scope:
      path: ""
    values:
      author: "Mr. Hyde"
      time: "2 min"
